"""
Agentic Labs - Goal-based lab definitions

Instead of scripted action sequences, these labs define GOALS.
The agent observes the screen and decides what action to take to achieve each goal.
"""

AGENTIC_LABS = {
    # === WORKING LABS ===

    "quick-demo": {
        "title": "30-Second Demo: Login and View ISPF",
        "description": "Quick demonstration of mainframe login and ISPF interface",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Demonstrate basic mainframe login via TN3270.",
                "success_criteria": ["READY"],
                "narration": "**Connected to MVS TK5**\n\nLogged in as HERC01 via TN3270 session.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Enter ISPF to view the menu",
                "context": "Type ISPF at READY prompt to enter the ISPF-like interface.",
                "success_criteria": ["BROWSE", "EDIT"],
                "narration": "**ISPF Primary Menu**\n\nOptions: 1=BROWSE, 2=EDIT, 3=UTILITIES",
                "control_plane": "tso",
                "max_actions": 8,
            },
            {
                "id": 3,
                "goal": "Exit ISPF back to READY prompt",
                "context": "Press PF3 to exit ISPF and return to TSO READY.",
                "success_criteria": ["READY"],
                "narration": "**Back to TSO READY**\n\nExited ISPF, now at command prompt.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 4,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO and return to the VTAM logon screen.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Demo complete.**\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "session-stack": {
        "title": "Session Stack: VTAM → TSO → ISPF",
        "description": "Map the session layers and trust boundaries on MVS 3.8j",
        "steps": [
            {
                "id": 1,
                "goal": "Connect to the mainframe via TN3270",
                "context": "We start at the VTAM session fabric - the lowest layer.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Layer 1: VTAM Session Fabric**\n\nConnected to VTAM. Identity not yet bound - anonymous session.",
                "control_plane": "vtam",
                "max_actions": 10,
            },
            {
                "id": 2,
                "goal": "Login to TSO as HERC01",
                "context": "TSO login binds our identity. RAKF verifies credentials.",
                "success_criteria": ["READY"],
                "narration": "**Layer 2: TSO - Identity Bound**\n\nNow running as HERC01. All commands use this authority.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 3,
                "goal": "Enter ISPF to view the interactive menu",
                "context": "ISPF is the interactive application layer on TK5.",
                "success_criteria": ["BROWSE", "EDIT"],
                "narration": "**Layer 3: ISPF - Interactive Desktop**\n\nISPF provides panels for browsing, editing, and utilities.",
                "control_plane": "tso",
                "max_actions": 8,
            },
            {
                "id": 4,
                "goal": "Use option 1 to enter Browse mode",
                "context": "Browse lets us view datasets without modifying them. On TK5 this is called REVIEW.",
                "success_criteria": ["REVIEW", "ENTRY"],
                "narration": "**Layer 4: Browse Function**\n\nBrowse mode - read-only access to datasets.",
                "control_plane": "tso",
                "max_actions": 8,
            },
            {
                "id": 5,
                "goal": "Exit Browse back to ISPF menu",
                "context": "Press PF3 to exit back to the ISPF menu.",
                "success_criteria": ["BROWSE", "EDIT"],
                "narration": "**Back to ISPF Menu**\n\nExiting layers one at a time.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 6,
                "goal": "Exit ISPF back to TSO READY",
                "context": "Press PF3 to exit ISPF and return to TSO.",
                "success_criteria": ["READY"],
                "narration": "**Back to TSO READY**\n\nLayer 3 exited, at TSO command prompt.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 7,
                "goal": "Logoff TSO and return to VTAM logon screen",
                "context": "Type LOGOFF to disconnect from TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Session Layers Complete:**\n1. VTAM - session fabric\n2. TSO - identity bound\n3. ISPF - interactive desktop\n4. Functions - browse/edit/utilities\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "dataset-model": {
        "title": "Dataset Model: Catalog Navigation",
        "description": "Explore the MVS dataset namespace and catalog structure",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Need to authenticate before browsing datasets.",
                "success_criteria": ["READY"],
                "narration": "**Logged in**\n\nReady to explore the dataset namespace.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "List all datasets in the catalog using LISTCAT",
                "context": "LISTCAT shows all catalog entries.",
                "success_criteria": ["CATALOG"],
                "narration": "**Master Catalog**\n\nLISTCAT displays the master catalog - index of all datasets.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "List datasets starting with SYS1 using LISTCAT LVL(SYS1)",
                "context": "Filter catalog to show only SYS1.* datasets.",
                "success_criteria": ["SYS1", "CATALOG"],
                "narration": "**SYS1 Namespace**\n\nSYS1.* contains system libraries - the operating system itself.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 4,
                "goal": "Browse dataset SYS1.PARMLIB to see its members",
                "context": "SYS1.PARMLIB is a PDS containing system parameters.",
                "success_criteria": ["PARMLIB"],
                "narration": "**SYS1.PARMLIB - Partitioned Dataset**\n\nA PDS contains multiple members. PARMLIB holds system config.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 5,
                "goal": "Exit the dataset browse and return to READY",
                "context": "Press PF3 to exit browse mode.",
                "success_criteria": ["READY"],
                "narration": "**Dataset Types:**\n- Sequential: single file\n- Partitioned (PDS): directory of members\n- VSAM: indexed access method",
                "control_plane": "tso",
                "max_actions": 8,
            },
            {
                "id": 6,
                "goal": "Browse SYS1.PROCLIB to see JCL procedures",
                "context": "SYS1.PROCLIB contains cataloged JCL procedures.",
                "success_criteria": ["PROCLIB"],
                "narration": "**SYS1.PROCLIB**\n\nCataloged procedures - reusable JCL templates.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 7,
                "goal": "Exit browse and return to READY prompt",
                "context": "Press ENTER to scroll through member list, then return to READY.",
                "success_criteria": ["READY"],
                "narration": "**Dataset Naming:**\n\nHLQ.MIDDLE.LLQ(MEMBER)\n- HLQ: High-Level Qualifier (owner)\n- MEMBER: only for PDS",
                "control_plane": "tso",
                "max_actions": 20,
            },
            {
                "id": 8,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Dataset Model Complete:**\n\nHierarchical namespace, catalog-managed, supports sequential/PDS/VSAM.\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "rakf-security": {
        "title": "RAKF Security: Users, Profiles & Privileges",
        "description": "Examine the RAKF security system on MVS 3.8j TK5",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "RAKF is the security system on TK5 MVS 3.8j.",
                "success_criteria": ["READY"],
                "narration": "**Establishing Identity**\n\nLogged in as HERC01. RAKF handles authentication on MVS 3.8j TK5.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Browse the file SYS1.SECURE.CNTL(USERS) to view the RAKF users table",
                "context": "SYS1.SECURE.CNTL(USERS) contains all user definitions with CLEARTEXT passwords.",
                "success_criteria": ["HERC01", "CUL8TR"],
                "narration": "**RAKF Users Table**\n\nBrowsing `SYS1.SECURE.CNTL(USERS)` - ALL users with CLEARTEXT passwords!\n\nFormat: `USERNAME GROUP *PASSWORD FLAGS`",
                "control_plane": "racf",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit the file viewer.",
                "success_criteria": ["READY"],
                "narration": "**Security Finding:**\n\nPasswords stored in cleartext - major vulnerability in RAKF.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 4,
                "goal": "Browse SYS1.SECURE.CNTL(PROFILES) to see access control rules",
                "context": "PROFILES defines which users/groups can access which resources.",
                "success_criteria": ["DATASET", "UACC"],
                "narration": "**RAKF Profiles Table**\n\nBrowsing `SYS1.SECURE.CNTL(PROFILES)` - the access control rules.\n\nUACC=READ means default read access for all.",
                "control_plane": "racf",
                "max_actions": 10,
            },
            {
                "id": 5,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit.",
                "success_criteria": ["READY"],
                "narration": "**RAKF Authorization:**\n\n- DATASET class: file access\n- UACC: Universal Access\n- No mandatory access control",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 6,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO cleanly.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**RAKF Summary:**\n\n1. Cleartext passwords in USERS table\n2. UACC=READ grants default read access\n3. No separation between admin levels\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "deferred-exec": {
        "title": "Deferred Execution: JCL → JES2",
        "description": "View job status and understand batch execution model",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Need to be logged in to view jobs.",
                "success_criteria": ["READY"],
                "narration": "**Setup**\n\nLogging in to demonstrate deferred execution via JES2.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Check job status using the STATUS command",
                "context": "STATUS shows all active jobs, started tasks, and TSO users.",
                "success_criteria": ["TSU"],
                "narration": "**JES2 Status**\n\nSTATUS shows:\n- JOB: Batch jobs\n- TSU: TSO users\n- STC: Started tasks (system services)",
                "control_plane": "jes",
                "max_actions": 8,
            },
            {
                "id": 3,
                "goal": "Browse SYS1.PROCLIB to see cataloged procedures",
                "context": "PROCs are reusable JCL templates stored in PROCLIB.",
                "success_criteria": ["PROCLIB"],
                "narration": "**Cataloged Procedures**\n\nPROCs define standard job steps that can be invoked by name.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 4,
                "goal": "Exit browse and return to READY prompt",
                "context": "Press PF3 to exit.",
                "success_criteria": ["READY"],
                "narration": "**JES2 Model:**\n\n1. Submit JCL → job queue\n2. JES2 schedules execution\n3. Output goes to spool\n4. Identity from JOB card, not submitter",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 5,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Deferred Execution Summary:**\n\nJobs run asynchronously. JES2 manages the job queue.\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "address-spaces": {
        "title": "Address Space Anatomy",
        "description": "View active address spaces and understand MVS memory isolation",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Need to authenticate to view system status.",
                "success_criteria": ["READY"],
                "narration": "**Logged in**\n\nReady to examine address spaces.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Use STATUS command to view all active address spaces",
                "context": "STATUS shows all jobs, TSO users, and started tasks.",
                "success_criteria": ["TSU"],
                "narration": "**Active Address Spaces**\n\nEach entry is a separate address space:\n- JOB: Batch job\n- TSU: TSO user\n- STC: System task",
                "control_plane": "tso",
                "max_actions": 8,
            },
            {
                "id": 3,
                "goal": "Browse SYS1.PARMLIB to see system parameters",
                "context": "PARMLIB controls address space creation and limits.",
                "success_criteria": ["PARMLIB"],
                "narration": "**System Parameters**\n\nPARMLIB members define:\n- Memory limits per address space\n- System initialization options\n- Security settings",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 4,
                "goal": "Exit browse and return to READY prompt",
                "context": "Press ENTER to scroll through member list, then return to READY.",
                "success_criteria": ["READY"],
                "narration": "**Address Space Isolation:**\n\nEach address space has:\n- Private memory region\n- Own TCBs (threads)\n- Cannot access other AS memory directly",
                "control_plane": "tso",
                "max_actions": 20,
            },
            {
                "id": 5,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**Address Space Summary:**\n\nMVS provides hardware-enforced isolation between address spaces.\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "system-inspection": {
        "title": "System Inspection: Configuration & Logging",
        "description": "Examine system configuration and SMF logging",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "HERC01 has OPERATIONS authority - can see everything.",
                "success_criteria": ["READY"],
                "narration": "**Logged in as HERC01**\n\nHERC01 has OPERATIONS authority - bypass most access checks.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Browse SYS1.PARMLIB(IEASYS00) to see IPL parameters",
                "context": "IEASYS00 defines system initialization parameters.",
                "success_criteria": ["IEASYS"],
                "narration": "**IPL Parameters**\n\nIEASYS00 controls:\n- Memory allocation\n- SMF options\n- APF authorized libraries\n- Subsystem initialization",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit the viewer.",
                "success_criteria": ["READY"],
                "narration": "**System Config Location:**\n\nAll config in SYS1.PARMLIB - know this, control the system.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 4,
                "goal": "Browse SYS1.PARMLIB(SMFPRM00) for SMF settings",
                "context": "SMF records all system activity for auditing.",
                "success_criteria": ["SMF"],
                "narration": "**SMF Parameters**\n\nSMF records:\n- Job start/end (types 4,5)\n- Dataset access (types 14-18)\n- Security events (types 80-83)",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 5,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit.",
                "success_criteria": ["READY"],
                "narration": "**SMF for Security:**\n\nSMF is the audit trail. Attackers may try to disable it.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 6,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**System Inspection Complete:**\n\nKey files:\n- IEASYS00: System init\n- SMFPRM00: Audit logging\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "cobol-basics": {
        "title": "COBOL Basics: View Source Code",
        "description": "Browse COBOL programs to understand mainframe development",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Need access to browse source libraries.",
                "success_criteria": ["READY"],
                "narration": "**Logged in**\n\nReady to explore COBOL source code.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "List the COBOL library SYS1.COBLIB and its members",
                "context": "SYS1.COBLIB is the COBOL runtime library on MVS 3.8j / TK5.",
                "success_criteria": ["COBLIB", "--RECFM-|MEMBERS|DSORG"],
                "narration": "**COBOL Libraries**\n\nCOBOL runtime lives in SYS1.COBLIB - a partitioned dataset (PDS) of members.",
                "control_plane": "tso",
                "max_actions": 12,
            },
            {
                "id": 3,
                "goal": "Return to READY prompt",
                "context": "Clear screen or press Enter to return to READY.",
                "success_criteria": ["READY"],
                "narration": "**COBOL Structure:**\n\n1. IDENTIFICATION DIVISION\n2. ENVIRONMENT DIVISION\n3. DATA DIVISION\n4. PROCEDURE DIVISION",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 4,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**COBOL Summary:**\n\nStill runs 95% of financial transactions worldwide.\nFixed-format columns: 1-6 sequence, 7 indicator, 8-72 code.\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "jcl-basics": {
        "title": "JCL Basics: Job Control Language",
        "description": "Browse JCL procedures and understand batch job structure",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "Need access to browse JCL libraries.",
                "success_criteria": ["READY"],
                "narration": "**Logged in**\n\nReady to explore JCL - the batch job control language.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Browse SYS1.PROCLIB to see system JCL procedures",
                "context": "SYS1.PROCLIB contains cataloged procedures used by system jobs.",
                "success_criteria": ["PROCLIB"],
                "narration": "**SYS1.PROCLIB**\n\nCataloged procedures (PROCs) - reusable JCL templates.\n\nKey members: ASMHCL, COBUCL, LNKEDT",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "Exit browse and return to READY prompt",
                "context": "Press ENTER to scroll through member list, then return to READY.",
                "success_criteria": ["READY"],
                "narration": "**JCL Card Types:**\n\n- JOB: Identifies job, accounting, class\n- EXEC: Runs program or PROC\n- DD: Defines dataset (input/output)",
                "control_plane": "tso",
                "max_actions": 20,
            },
            {
                "id": 4,
                "goal": "Browse SYS2.JCLLIB to see sample JCL",
                "context": "SYS2.JCLLIB contains sample JCL for learning.",
                "success_criteria": ["JCLLIB"],
                "narration": "**Sample JCL**\n\nUser JCL libraries contain job examples and templates.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 5,
                "goal": "Exit browse and return to READY prompt",
                "context": "Press ENTER to scroll through member list, then return to READY.",
                "success_criteria": ["READY"],
                "narration": "**JCL Execution:**\n\n1. Submit to JES2 input queue\n2. JES2 allocates datasets\n3. Programs execute in order\n4. Output to spool",
                "control_plane": "tso",
                "max_actions": 20,
            },
            {
                "id": 6,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**JCL Summary:**\n\nEvery batch job starts with JCL. Controls:\n- What programs run\n- What data they use\n- Where output goes\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "auth-model": {
        "title": "Authorization Model: RAKF Deep Dive",
        "description": "Deep dive into RAKF authorization on TK5",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "HERC01 has OPERATIONS authority - can see everything.",
                "success_criteria": ["READY"],
                "narration": "**HERC01 Authority**\n\nOPERATIONS=Y means bypass most access checks.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Browse SYS1.SECURE.CNTL(USERS) to see all userids",
                "context": "USERS table defines all accounts and passwords.",
                "success_criteria": ["HERC01", "CUL8TR"],
                "narration": "**User Definitions**\n\nEach line: USERID GROUP PASSWORD FLAGS\n\nFlags: O=OPERATIONS, S=SPECIAL, A=AUDITOR",
                "control_plane": "racf",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit.",
                "success_criteria": ["READY"],
                "narration": "**Security Note:**\n\nAll passwords visible in cleartext - RAKF weakness.",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 4,
                "goal": "Browse SYS1.SECURE.CNTL(PROFILES) to see access rules",
                "context": "PROFILES defines access rules by class.",
                "success_criteria": ["DATASET", "UACC"],
                "narration": "**Access Rules**\n\nDATASET class controls file access.\nUACC=READ is the default - everyone can read.",
                "control_plane": "racf",
                "max_actions": 10,
            },
            {
                "id": 5,
                "goal": "Exit file and return to READY prompt",
                "context": "Press PF3 to exit.",
                "success_criteria": ["READY"],
                "narration": "**Authorization Model:**\n\n1. Check explicit access first\n2. Then group access\n3. Finally UACC (Universal Access)",
                "control_plane": "tso",
                "max_actions": 5,
            },
            {
                "id": 6,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**RAKF Authorization Summary:**\n\n1. Profiles grant access, not userids\n2. No root user - distributed authority\n3. UACC=READ means anyone can read by default\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },

    "cics-kicks": {
        "title": "CICS/KICKS: Transaction Processing",
        "description": "Explore the KICKS CICS emulator on TK5 (REQUIRES KICKS INSTALLED)",
        "disabled": True,
        "disabled_reason": "KICKS CICS emulator not installed on this TK5 instance",
        "steps": [
            {
                "id": 1,
                "goal": "Connect and login to TSO as HERC01",
                "context": "KICKS is accessed from TSO.",
                "success_criteria": ["READY"],
                "narration": "**Logged in**\n\nReady to enter KICKS CICS region.",
                "control_plane": "tso",
                "max_actions": 15,
            },
            {
                "id": 2,
                "goal": "Enter the KICKS CICS region by typing KICKS",
                "context": "KICKS is TK5's CICS emulator.",
                "success_criteria": ["DFHSM", "CICS"],
                "narration": "**KICKS Region**\n\nKICKS emulates CICS for transaction processing.",
                "control_plane": "cics",
                "max_actions": 10,
            },
            {
                "id": 3,
                "goal": "Exit KICKS and return to TSO",
                "context": "Type CESF LOGOFF to exit KICKS.",
                "success_criteria": ["READY"],
                "narration": "**Back to TSO**\n\nExited KICKS CICS region.",
                "control_plane": "tso",
                "max_actions": 10,
            },
            {
                "id": 4,
                "goal": "Logoff and return to VTAM logon screen",
                "context": "Type LOGOFF to exit TSO.",
                "success_criteria": ["ENTER USERID|LOGON ===>|IKJ56700A"],
                "narration": "**CICS Summary:**\n\nTransaction processing - each transaction is isolated.\n\nReturned to VTAM logon screen.",
                "control_plane": "vtam",
                "max_actions": 8,
            },
        ],
    },
}
